export function generateSvelteFile(uiTree: any, designTokens: any): string {
  const reverseColorMap: Record<string, string> = {};
  if (designTokens?.colors) {
    for (const [key, val] of Object.entries(designTokens.colors)) {
      reverseColorMap[val as string] = key;
    }
  }

  const reverseFontMap: Record<string, string> = {};
  if (designTokens?.fonts) {
    for (const [key, val] of Object.entries(designTokens.fonts)) {
      reverseFontMap[val as string] = key;
    }
  }

  function getClasses(node: any): string[] {
    const classes: string[] = [];
    if (node.styles) {
      const bg = node.styles.backgroundColor;
      if (bg && bg !== 'transparent' && bg !== 'rgba(0, 0, 0, 0)') {
        const token = reverseColorMap[bg];
        classes.push(token ? `bg-${token}` : `bg-[${bg}]`);
      }
      const c = node.styles.color;
      if (c && c !== 'transparent' && c !== 'rgba(0, 0, 0, 0)') {
        const token = reverseColorMap[c];
        classes.push(token ? `text-${token}` : `text-[${c}]`);
      }
      const p = node.styles.padding;
      if (p && p !== '0px') {
        classes.push(`p-[${p}]`);
      }
      const f = node.styles.fontSize;
      if (f) {
        const token = reverseFontMap[f];
        classes.push(token ? `text-${token}` : `text-[${f}]`);
      }
    }
    
    return classes;
  }

  function renderNode(node: any, indentLevel: number): string {
    const pad = '  '.repeat(indentLevel);
    const tag = node.tagName?.toLowerCase() || 'div';
    
    let attrs = '';
    if (node.id) attrs += ` id="${node.id}"`;

    const cls = getClasses(node);
    if (cls.length > 0) attrs += ` class="${cls.join(' ')}"`;

    if (!node.children || node.children.length === 0) {
      if (node.text) {
        return `${pad}<${tag}${attrs}>${node.text.trim()}</${tag}>\n`;
      }
      return `${pad}<${tag}${attrs} />\n`;
    }

    let result = `${pad}<${tag}${attrs}>\n`;
    if (node.text && node.text.trim()) {
      result += `${pad}  ${node.text.trim()}\n`;
    }

    for (const child of node.children) {
      result += renderNode(child, indentLevel + 1);
    }

    result += `${pad}</${tag}>\n`;
    return result;
  }

  const scriptStr = `<script lang="ts">\n  // Generated by UIKey Svelte Generator\n</script>\n\n`;
  const markupStr = renderNode(uiTree, 0) + `\n`;
  
  let styleStr = `<style>\n`;
  if (designTokens?.themes?.dark) {
    styleStr += `  /* Dark mode overrides would go here */\n`;
  }
  styleStr += `</style>\n`;

  return scriptStr + markupStr + styleStr;
}
